# Podfile
platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  flutter_root = File.expand_path(File.join(_dir_, '..', 'flutter'))
  unless File.exist?(flutter_root)
    raise "Flutter not found at #{flutter_root}. Run 'flutter precache'."
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_installation

  flutter_install_all_ios_pods File.dirname(File.realpath(_FILE_))
end
